events {
    worker_connections 1024;
}

http {
    # 1. On pointe vers ton conteneur API qui écoute sur le port 3000
    upstream nestjs_api {
        server api:3000;
    }

    # 2. Redirection forcée : On renvoie les visiteurs du HTTP vers le HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # 3. Le serveur HTTPS Principal (Le vigile)
    server {
        listen 443 ssl;
        server_name localhost;

        # On lui donne les clés que tu viens de générer !
        ssl_certificate /etc/nginx/certs/selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;

        # 🛡️ HEADERS DE SÉCURITÉ (Ça, c'est pour les points du barème d'Alex !)
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";

        # 🚀 On laisse passer le trafic normal vers NestJS
        location / {
            proxy_pass http://nestjs_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 🔌 On autorise les WebSockets (Encore des points pour le barème !)
        location /socket.io/ {
            proxy_pass http://nestjs_api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}